// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Launch(arg1, arg2) {
  return window['go']['main']['App']['Launch'](arg1, arg2);
}
