name: Build & Release Latest

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Adjust to your Go version if needed

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update

          # Try to install libwebkit2gtk-4.0-dev first, fallback to libwebkit2gtk-4.1-dev
          if apt-cache show libwebkit2gtk-4.0-dev >/dev/null 2>&1; then
            sudo apt install -y libwebkit2gtk-4.0-dev
          else
            sudo apt install -y libwebkit2gtk-4.1-dev
          fi

          sudo apt install -y \
            libgtk-3-dev \
            libglib2.0-dev \
            libnotify-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libgdk-pixbuf2.0-dev \
            libxi-dev \
            libxtst-dev \
            pkg-config \
            wget \
            ca-certificates

      - name: Install Wails
        run: |
            go install github.com/wailsapp/wails/v2/cmd/wails@latest
        shell: bash

      - name: Build app
        run: |
            wails build -platform all

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: build/bin/**/*

  release:
    name: Create Latest Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare Release Assets
        run: |
          mkdir -p release
          cp -r artifacts/*/* release/

      - name: Create or Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Latest
          name: Latest
          body: "Automatic rolling build from master branch."
          draft: false
          prerelease: false
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
